language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

install:
  - go get -t -v -d -u ./...

before_install:
  - go get -t -v -d -u github.com/DrmagicE/gmqtt

script:
  -  go test -race ./pkg/packets
  -  go test -race .  -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
