listeners:
    - address: ":1883"
    - address: ":8883"
      websocket:
        path: "/"
mqtt:
  session_expiry: 2h
  session_expiry_check_timer: 20s
  message_expiry: 2h
  max_packet_size: 0 # 0 means no limit
  server_receive_maximum: 100
  max_keepalive: 60
  topic_alias_maximum: 10
  subscription_identifier_available: true
  wildcard_subscription_available: true
  shared_subscription_available: true
  maximum_qos: 2
  retain_available: true
  max_queued_messages: 1000
  max_inflight: 100
  max_awaiting_rel: 100
  queue_qos0_messages: true
  delivery_mode: onlyonce # overlap or onlyonce
  allow_zero_length_clientid: true

plugins:
  prometheus:
    path: "/metrics"
    listen_address: ":8082"

log:
  level: warn # debug | info | warn | error





