# Path to pid file, default to /var/run/gmqttd.pid
# pid_file:

listeners:
  # bind address
  - address: ":1883"
#    tls:
#      cacert: "path_to_ca_cert_file"
#      cert: "path_to_cert_file"
#      key: "path_to_key_file"

  - address: ":8883"
    # websocket setting
    websocket:
      path: "/"

api:
  grpc:
    - address: "unix:///var/run/gmqttd.sock" # The gRPC server listen address.
#      tls:
#        cacert: "path_to_ca_cert_file"
#        cert: "path_to_cert_file"
#        key: "path_to_key_file"
  http:
      # The HTTP server listen address. This is a reverse-proxy server in front of gRPC server.
    - address: "tcp://127.0.0.1:8083"
      map: "unix:///var/run/gmqttd.sock" # The backend gRPC server endpoint,
#      tls:
#        cacert: "path_to_ca_cert_file"
#        cert: "path_to_cert_file"
#        key: "path_to_key_file"

mqtt:
  session_expiry: 2h
  session_expiry_check_timer: 20s
  message_expiry: 2h
  max_packet_size: 268435456
  server_receive_maximum: 100
  max_keepalive: 60
  topic_alias_maximum: 10
  subscription_identifier_available: true
  wildcard_subscription_available: true
  shared_subscription_available: true
  maximum_qos: 2
  retain_available: true
  max_queued_messages: 1000
  max_inflight: 100
  queue_qos0_messages: true
  delivery_mode: onlyonce # overlap or onlyonce
  allow_zero_length_clientid: true

persistence:
  type: memory  # memory | redis
  # The redis configuration only take effect when type == redis.
  redis:
    # redis server address
    addr: "127.0.0.1:6379"
    # the maximum number of idle connections in the redis connection pool.
    max_idle: 1000
    # the maximum number of connections allocated by the redis connection pool at a given time.
    # If zero, there is no limit on the number of connections in the pool.
    max_active: 0
    # the connection idle timeout, connection will be closed after remaining idle for this duration. If the value is zero, then idle connections are not closed.
    idle_timeout: 240s
    password: ""
    # the number of the redis database.
    database: 0

# The topic alias manager setting. The topic alias feature is introduced by MQTT V5.
# This setting is used to control how the broker manage topic alias.
topic_alias_manager:
  # Currently, only FIFO strategy is supported.
  type: fifo

plugins:
  prometheus:
    path: "/metrics"
    listen_address: ":8082"
  auth:
    # Password hash type. (plain | md5 | sha256 | bcrypt)
    # Default to MD5.
    hash: md5
    # The file to store password. If it is a relative path, it locates in the same directory as the config file.
    # (e.g: ./gmqtt_password => /etc/gmqtt/gmqtt_password.yml)
    # Default to ./gmqtt_password.yml
    # password_file:

# plugin loading orders
plugin_order:
  # Uncomment auth to enable authentication.
  # - auth
  - prometheus
  - admin
log:
  level: info # debug | info | warn | error
  format: text # json | text
  # whether to dump MQTT packet in debug level
  dump_packet: false




